# Generated by Django 6.0.2 on 2026-03-02 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_emailotp_attempts_alter_emailotp_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
